---
pipeline:
  setup:
    image: golang
    group: test
    when:
      event: [push]
    commands:
      - go get -v
  test:
    image: golang
    group: test
    when:
      event: [push]
    commands:
      - go test main.go handler.go
  build:
    image: golang
    group: test
    when:
      event: [push]
    commands:
      - go build main.go handler.go
  docker:
    image: plugins/docker
    when:
      branch:
        - prod
      event: push
      status: success
    registry: https://registry.abakus.no
    repo: registry.abakus.no/webkom/readme-as-a-function
    dockerfile: Dockerfile
    secrets: [docker_username, docker_password]
    tags:
      - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
      - latest
    build_args:
      - RELEASE=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
