---
pipeline:
  test:
    image: golang
    group: test
    when:
      event: [push]
    commands:
      # TODO fix this hack
      - go get -v -u github.com/PuerkitoBio/goquery
      - go get -v -u github.com/graph-gophers/graphql-go
      - go test hander_test.go handler.go
  build:
    image: golang
    group: test
    when:
      event: [push]
    commands:
      - go get -v -u github.com/PuerkitoBio/goquery
      - go get -v -u github.com/graph-gophers/graphql-go
      - go build main.go handler.go
  docker:
    image: plugins/docker
    when:
      branch:
        - prod
      event: push
      status: success
    registry: https://registry.abakus.no
    repo: registry.abakus.no/webkom/readme-as-a-function
    dockerfile: Dockerfile
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
      - latest
    build_args:
      - RELEASE=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
